services:
  - type: web
    name: saascollectiveplayer
    env: node
    plan: free
    region: oregon

    # Set up the build and start commands
    buildCommand: npm install && npm run vercel-build
    startCommand: npm start

    # Environment variables
    envVars:
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL
      - key: SUPABASE_URL
        value: YOUR_SUPABASE_URL
      - key: SUPABASE_ANON_KEY
        value: YOUR_SUPABASE_ANON_KEY
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: YOUR_SUPABASE_SERVICE_ROLE_KEY

    # Define any health checks (you can update the path if needed)
    healthCheckPath: /

    # Specify any additional options or settings if needed
    autoDeploy: true
    branch: main
